# Generated by Django 3.2.7 on 2021-10-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(default='project_name', max_length=50)),
                ('project_description', models.CharField(default='project description', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_name', models.CharField(default='default simulation', max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='simulation_name',
        ),
    ]
