# Generated by Django 3.2.7 on 2021-10-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0003_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
