# Generated by Django 3.2.7 on 2021-10-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0005_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='irene@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='irene1234', max_length=15),
        ),
    ]
