# Generated by Django 3.2.7 on 2021-10-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0006_auto_20211006_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='project',
        ),
        migrations.RemoveField(
            model_name='details',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(default='Project Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(default='Project Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='simulation_name',
            field=models.CharField(default='Simulation Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='Email', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='Password', max_length=15),
        ),
    ]
